spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rain-R/springcloud_sell/
          username: Rain-R
          password: wz,1314,wz
          search-paths: config-repo
#          basedir: /Users/admin/code/myProjects/java/imooc/SpringCloud_Sell/config/basedir
#          basedir: F:\spring-cloud-workspace\springcloud_sell\config-repo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      expose: "*"
