spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
 #Spring Data JPA
  jpa:
    database: mysql
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/